//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamePayDBEntities : DbContext
    {
        public GamePayDBEntities()
            : base("name=GamePayDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<record_AllResendOrder> record_AllResendOrder { get; set; }
        public virtual DbSet<record_Annc> record_Annc { get; set; }
        public virtual DbSet<record_Area> record_Area { get; set; }
        public virtual DbSet<record_AttachBonus> record_AttachBonus { get; set; }
        public virtual DbSet<record_BasicBonus> record_BasicBonus { get; set; }
        public virtual DbSet<record_CashFlow> record_CashFlow { get; set; }
        public virtual DbSet<record_CashOutBatch> record_CashOutBatch { get; set; }
        public virtual DbSet<record_CashOutOrder> record_CashOutOrder { get; set; }
        public virtual DbSet<record_ExBonus> record_ExBonus { get; set; }
        public virtual DbSet<record_FloatImg> record_FloatImg { get; set; }
        public virtual DbSet<record_GoodsBonus> record_GoodsBonus { get; set; }
        public virtual DbSet<record_Group> record_Group { get; set; }
        public virtual DbSet<record_Login> record_Login { get; set; }
        public virtual DbSet<record_Npc> record_Npc { get; set; }
        public virtual DbSet<record_Operation> record_Operation { get; set; }
        public virtual DbSet<record_Order> record_Order { get; set; }
        public virtual DbSet<record_OrderItem> record_OrderItem { get; set; }
        public virtual DbSet<record_PlayerMsg> record_PlayerMsg { get; set; }
        public virtual DbSet<record_Refund> record_Refund { get; set; }
        public virtual DbSet<record_ScoreBonus> record_ScoreBonus { get; set; }
        public virtual DbSet<record_SingleResendOrder> record_SingleResendOrder { get; set; }
        public virtual DbSet<sys_Config> sys_Config { get; set; }
        public virtual DbSet<sys_ErrorLog> sys_ErrorLog { get; set; }
        public virtual DbSet<sys_LoginWhiteList> sys_LoginWhiteList { get; set; }
        public virtual DbSet<sys_Menu> sys_Menu { get; set; }
        public virtual DbSet<sys_MerchantFeeRate> sys_MerchantFeeRate { get; set; }
        public virtual DbSet<sys_PayAccount> sys_PayAccount { get; set; }
        public virtual DbSet<sys_Theme> sys_Theme { get; set; }
        public virtual DbSet<sys_User> sys_User { get; set; }
        public virtual DbSet<sys_UserAccount> sys_UserAccount { get; set; }
        public virtual DbSet<type_BankCode> type_BankCode { get; set; }
        public virtual DbSet<type_Bonus> type_Bonus { get; set; }
        public virtual DbSet<type_CashOutBatchStatus> type_CashOutBatchStatus { get; set; }
        public virtual DbSet<type_CashOutTarget> type_CashOutTarget { get; set; }
        public virtual DbSet<type_CashOutTransWay> type_CashOutTransWay { get; set; }
        public virtual DbSet<type_CashRecord> type_CashRecord { get; set; }
        public virtual DbSet<type_Engine> type_Engine { get; set; }
        public virtual DbSet<type_FloatHtml> type_FloatHtml { get; set; }
        public virtual DbSet<type_Gateway> type_Gateway { get; set; }
        public virtual DbSet<type_Item> type_Item { get; set; }
        public virtual DbSet<type_Msg> type_Msg { get; set; }
        public virtual DbSet<type_Operation> type_Operation { get; set; }
        public virtual DbSet<type_OperationWay> type_OperationWay { get; set; }
        public virtual DbSet<type_OrderStatus> type_OrderStatus { get; set; }
        public virtual DbSet<type_Pay> type_Pay { get; set; }
        public virtual DbSet<type_PayWay> type_PayWay { get; set; }
        public virtual DbSet<type_RefundStatus> type_RefundStatus { get; set; }
        public virtual DbSet<type_Script> type_Script { get; set; }
        public virtual DbSet<type_UserStatus> type_UserStatus { get; set; }
        public virtual DbSet<type_YeepayBankId> type_YeepayBankId { get; set; }
        public virtual DbSet<type_Order> type_Order { get; set; }
    }
}
