//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class record_AttachBonus
    {
        public long ID { get; set; }
        public long AreaID { get; set; }
        public string Name { get; set; }
        public string Cmd { get; set; }
        public long Rate { get; set; }
        public string BonusTypeStr { get; set; }
        public bool IsCurrency { get; set; }
        public bool ShowMsg { get; set; }
    }
}
