//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class record_SingleResendOrder
    {
        public int ID { get; set; }
        public long AreaId { get; set; }
        public short PayWayId { get; set; }
        public string OrderNo { get; set; }
        public short TotalFee { get; set; }
        public string GameAccount { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedTime { get; set; }
        public byte Status { get; set; }
        public string RuleInfo { get; set; }
    }
}
