//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class record_OrderItem
    {
        public long ID { get; set; }
        public string OrderNo { get; set; }
        public string ItemName { get; set; }
        public string CmdName { get; set; }
        public long Count { get; set; }
        public byte ItemTypeId { get; set; }
        public byte OrderType { get; set; }
    }
}
