//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class record_Npc
    {
        public long ID { get; set; }
        public long AreaId { get; set; }
        public string Name { get; set; }
        public string Mark { get; set; }
        public string Locations { get; set; }
        public short Num1 { get; set; }
        public short Apperance { get; set; }
        public short Num3 { get; set; }
        public short Num4 { get; set; }
        public short Num5 { get; set; }
        public short Num6 { get; set; }
    }
}
