//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_MerchantFeeRate
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public short PayWayID { get; set; }
        public decimal FeeRate { get; set; }
        public bool IsValid { get; set; }
    }
}
