//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_PayAccount
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mark { get; set; }
        public string MerId { get; set; }
        public string AppId { get; set; }
        public string Key { get; set; }
        public string Account { get; set; }
        public string SellerName { get; set; }
    }
}
