//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_Script
    {
        public byte ID { get; set; }
        public string Name { get; set; }
        public string Mark { get; set; }
        public byte EngineID { get; set; }
        public string CommonScript { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string FilePath { get; set; }
        public bool IsAppend { get; set; }
        public bool NeedTxtFileToRead { get; set; }
        public bool NeedTxtFileToSave { get; set; }
    }
}
